vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "<C-f>", vim.cmd.wa)
vim.keymap.set("n", "<leader>w", vim.cmd.wq)
vim.keymap.set("n", "<leader>b", "<cmd>q!<CR>")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
